version: 2

updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: ":arrow_up:"
    open-pull-requests-limit: 50

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: ":arrow_up:"
    open-pull-requests-limit: 50
